# Generated by Django 2.2.8 on 2019-12-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardPage',
        ),
    ]
